source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'RAMPaperSwitch', '~> 0.0.3'
pod 'SwiftMoment'
pod 'MXParallaxHeader'
pod 'AMScrollingNavbar'
pod 'SKPhotoBrowser'
pod 'LTMorphingLabel'
pod 'SwiftHEXColors'
pod 'PullToBounce'
pod 'DGElasticPullToRefresh'
pod 'Alamofire', '~> 3.0'
pod 'AlamofireImage', '~> 2.0'
pod 'PKHUD'
pod 'RAMAnimatedTabBarController', '~> 1.2.2'
pod 'NVActivityIndicatorView'
pod 'UMengAnalytics-NO-IDFA'
pod 'SwiftyJSON'
pod 'Kanna', '~> 1.0.0'
pod 'UMengSocialCOM', '~> 5.2.1'
